load("@bazel_skylib//lib:selects.bzl", "selects")
load("@bazel_skylib//rules:write_file.bzl", "write_file")
load("@tbox//bazel:common.bzl", "GLOBAL_COPTS", "GLOBAL_LINKOPTS", "GLOBAL_LOCAL_DEFINES", "template_rule")

package(default_visibility = ["//visibility:public"])

COPTS = GLOBAL_COPTS + select({
    "@tbox//bazel:not_cross_compiling_on_windows": [],
    "//conditions:default": [],
}) + select({
    "@platforms//os:linux": [],
    "@platforms//os:osx": [],
    "@platforms//os:windows": [],
    "//conditions:default": [],
})

LOCAL_DEFINES = GLOBAL_LOCAL_DEFINES + select({
    "@tbox//bazel:not_cross_compiling_on_windows": [],
    "//conditions:default": [],
}) + select({
    "@platforms//os:linux": [],
    "@platforms//os:osx": [],
    "@platforms//os:windows": [],
    "//conditions:default": [],
})

LINKOPTS = GLOBAL_LINKOPTS + select({
    "@tbox//bazel:not_cross_compiling_on_windows": [],
    "//conditions:default": [],
}) + select({
    "@platforms//os:linux": [],
    "@platforms//os:osx": [],
    "@platforms//os:windows": [],
    "//conditions:default": [],
})

cc_library(
    name = "aws-cpp-sdk-core",
    srcs = glob(
        [
            "crt/aws-crt-cpp/crt/aws-c-auth/source/**/*.c",
            "crt/aws-crt-cpp/crt/aws-c-cal/source/**/*.c",
            "crt/aws-crt-cpp/crt/aws-c-common/source/**/*.c",
            "crt/aws-crt-cpp/crt/aws-c-compression/source/**/*.c",
            "crt/aws-crt-cpp/crt/aws-c-event-stream/source/**/*.c",
            "crt/aws-crt-cpp/crt/aws-c-http/source/**/*.c",
            "crt/aws-crt-cpp/crt/aws-c-io/source/**/*.c",
            "crt/aws-crt-cpp/crt/aws-c-mqtt/source/**/*.c",
            "crt/aws-crt-cpp/crt/aws-c-s3/source/**/*.c",
            "crt/aws-crt-cpp/crt/aws-c-sdkutils/source/**/*.c",
            "crt/aws-crt-cpp/crt/aws-checksums/source/**/*.c",
            "crt/aws-crt-cpp/crt/s2n/api/**/*.c",
            "crt/aws-crt-cpp/crt/s2n/crypto/**/*.c",
            "crt/aws-crt-cpp/crt/s2n/error/**/*.c",
            "crt/aws-crt-cpp/crt/s2n/stuffer/**/*.c",
            "crt/aws-crt-cpp/crt/s2n/tls/**/*.c",
            "crt/aws-crt-cpp/crt/s2n/utils/**/*.c",
            "crt/aws-crt-cpp/source/**/*.cpp",
            "src/aws-cpp-sdk-core/source/**/*.cpp",
        ],
        exclude = [
            "crt/aws-crt-cpp/crt/**/source/**/android/**/*.c",
            "crt/aws-crt-cpp/crt/**/source/**/bsd/**/*.c",
            "crt/aws-crt-cpp/crt/**/source/**/darwin/**/*.c",
            "crt/aws-crt-cpp/crt/**/source/**/windows/**/*.c",
            "crt/aws-crt-cpp/crt/**/source/**/linux/**/*.c",
            "crt/aws-crt-cpp/crt/aws-c-common/source/arch/**/*.c",
            "crt/aws-crt-cpp/crt/aws-c-common/source/platform_fallback_stubs/**/*.c",
            "crt/aws-crt-cpp/crt/aws-checksums/source/arm/**/*.c",
            "crt/aws-crt-cpp/crt/aws-checksums/source/generic/**/*.c",
            "crt/aws-crt-cpp/crt/aws-checksums/source/intel/**/*.c",
            "src/aws-cpp-sdk-core/source/net/linux-shared/**/*.cpp",
            "src/aws-cpp-sdk-core/source/**/android/**/*.cpp",
            "src/aws-cpp-sdk-core/source/**/bsd/**/*.cpp",
            "src/aws-cpp-sdk-core/source/**/darwin/**/*.cpp",
            "src/aws-cpp-sdk-core/source/**/linux/**/*.cpp",
            "src/aws-cpp-sdk-core/source/**/windows/**/*.cpp",
            "src/aws-cpp-sdk-core/source/smithy/tracing/impl/opentelemetry/**/*.cpp",
        ],
    ) + select({
        "@platforms//os:linux": glob([
            "crt/aws-crt-cpp/crt/**/source/**/linux/**/*.c",
            "crt/aws-crt-cpp/crt/aws-checksums/source/intel/asm/*.c",
            "crt/aws-crt-cpp/crt/aws-c-common/source/arch/intel/*.c",
            "crt/aws-crt-cpp/crt/aws-c-common/source/arch/intel/asm/*.c",
            "src/aws-cpp-sdk-core/source/**/linux/**/*.cpp",
        ]),
        "@platforms//os:osx": [],
        "@platforms//os:windows": [],
        "//conditions:default": [],
    }),
    hdrs = glob([
        "crt/aws-crt-cpp/crt/aws-c-auth/include/**/*.h",
        "crt/aws-crt-cpp/crt/aws-c-cal/include/**/*.h",
        "crt/aws-crt-cpp/crt/aws-c-common/include/**/*.h",
        "crt/aws-crt-cpp/crt/aws-c-common/include/**/*.inl",
        "crt/aws-crt-cpp/crt/aws-c-common/source/external/**/*.h",
        "crt/aws-crt-cpp/crt/aws-c-compression/include/**/*.h",
        "crt/aws-crt-cpp/crt/aws-c-event-stream/include/**/*.h",
        "crt/aws-crt-cpp/crt/aws-c-http/include/**/*.h",
        "crt/aws-crt-cpp/crt/aws-c-http/include/**/*.def",
        "crt/aws-crt-cpp/crt/aws-c-io/include/**/*.h",
        "crt/aws-crt-cpp/crt/aws-c-io/source/**/*.h",
        "crt/aws-crt-cpp/crt/aws-c-mqtt/include/**/*.h",
        "crt/aws-crt-cpp/crt/aws-c-s3/include/**/*.h",
        "crt/aws-crt-cpp/crt/aws-c-sdkutils/include/**/*.h",
        "crt/aws-crt-cpp/crt/aws-checksums/include/**/*.h",
        "crt/aws-crt-cpp/crt/s2n/api/**/*.h",
        "crt/aws-crt-cpp/crt/s2n/crypto/**/*.h",
        "crt/aws-crt-cpp/crt/s2n/error/**/*.h",
        "crt/aws-crt-cpp/crt/s2n/stuffer/**/*.h",
        "crt/aws-crt-cpp/crt/s2n/tls/**/*.h",
        "crt/aws-crt-cpp/crt/s2n/utils/**/*.h",
        "crt/aws-crt-cpp/include/**/*.h",
        "src/aws-cpp-sdk-core/include/**/*.h",
    ]) + [
        ":config_h",
        ":crt_config_h",
    ],
    copts = COPTS + [
        "-I$(GENDIR)/external/aws_sdk/crt/aws-crt-cpp/crt/aws-c-common/include",
        "-I$(GENDIR)/external/aws_sdk/crt/aws-crt-cpp/include",
        "-mavx2",
    ],
    includes = [
        "crt/aws-crt-cpp/crt/aws-c-auth/include",
        "crt/aws-crt-cpp/crt/aws-c-cal/include",
        "crt/aws-crt-cpp/crt/aws-c-common/include",
        "crt/aws-crt-cpp/crt/aws-c-common/source",
        "crt/aws-crt-cpp/crt/aws-c-common/source/external/libcbor",
        "crt/aws-crt-cpp/crt/aws-c-compression/include",
        "crt/aws-crt-cpp/crt/aws-c-event-stream/include",
        "crt/aws-crt-cpp/crt/aws-c-http/include",
        "crt/aws-crt-cpp/crt/aws-c-io/include",
        "crt/aws-crt-cpp/crt/aws-c-io/source",
        "crt/aws-crt-cpp/crt/aws-c-mqtt/include",
        "crt/aws-crt-cpp/crt/aws-c-s3/include",
        "crt/aws-crt-cpp/crt/aws-c-sdkutils/include",
        "crt/aws-crt-cpp/crt/aws-checksums/include",
        "crt/aws-crt-cpp/crt/s2n",
        "crt/aws-crt-cpp/crt/s2n/api",
        "crt/aws-crt-cpp/include",
        "src/aws-cpp-sdk-core/include",
    ],
    linkopts = LINKOPTS,
    local_defines = LOCAL_DEFINES + [
        "AWS_AFFINITY_METHOD=AWS_AFFINITY_METHOD_PTHREAD_ATTR",
        "AWS_COMMON_EXPORTS",
        "AWS_COMMON_USE_IMPORT_EXPORT",
        "AWS_PTHREAD_GETNAME_TAKES_3ARGS",
        "AWS_PTHREAD_SETNAME_TAKES_2ARGS",
        "AWS_TEST_REGION=US_EAST_1",
        "CJSON_HIDE_SYMBOLS",
        "ENABLED_REQUEST_COMPRESSION",
        "ENABLED_ZLIB_REQUEST_COMPRESSION",
        "ENABLE_CURL_CLIENT",
        "ENFORCE_TLS_V1_2",
        "HAVE_SYSCONF",
        "INTEL_NO_ITTNOTIFY_API",
        "PLATFORM_LINUX",
        "USE_SIMD_ENCODING",
        "_POSIX_C_SOURCE=200809L",
        "_XOPEN_SOURCE=500",
        "USE_S2N",
    ],
    deps = ["@curl"],
)

cc_library(
    name = "aws-cpp-sdk-route53",
    srcs = glob([
        "generated/src/aws-cpp-sdk-route53/source/**/*.cpp",
        "generated/src/aws-cpp-sdk-route53resolver/source/**/*.cpp",
        "generated/src/aws-cpp-sdk-route53profiles/source/**/*.cpp",
        "generated/src/aws-cpp-sdk-route53domains/source/**/*.cpp",
        "generated/src/aws-cpp-sdk-route53-recovery-readiness/source/**/*.cpp",
        "generated/src/aws-cpp-sdk-route53-recovery-control-config/source/**/*.cpp",
        "generated/src/aws-cpp-sdk-route53-recovery-cluster/source/**/*.cpp",
    ]),
    hdrs = glob([
        "generated/src/aws-cpp-sdk-route53/include/**/*.h",
        "generated/src/aws-cpp-sdk-route53resolver/include/**/*.h",
        "generated/src/aws-cpp-sdk-route53profiles/include/**/*.h",
        "generated/src/aws-cpp-sdk-route53domains/include/**/*.h",
        "generated/src/aws-cpp-sdk-route53-recovery-readiness/include/**/*.h",
        "generated/src/aws-cpp-sdk-route53-recovery-control-config/include/**/*.h",
        "generated/src/aws-cpp-sdk-route53-recovery-cluster/include/**/*.h",
    ]),
    copts = COPTS,
    includes = [
        "generated/src/aws-cpp-sdk-route53-recovery-cluster/include",
        "generated/src/aws-cpp-sdk-route53-recovery-control-config/include",
        "generated/src/aws-cpp-sdk-route53-recovery-readiness/include",
        "generated/src/aws-cpp-sdk-route53/include",
        "generated/src/aws-cpp-sdk-route53domains/include",
        "generated/src/aws-cpp-sdk-route53profiles/include",
        "generated/src/aws-cpp-sdk-route53resolver/include",
    ],
    linkopts = LINKOPTS,
    local_defines = LOCAL_DEFINES + [
        "AWS_AFFINITY_METHOD=AWS_AFFINITY_METHOD_PTHREAD_ATTR",
        "AWS_COMMON_EXPORTS",
        "AWS_COMMON_USE_IMPORT_EXPORT",
        "AWS_PTHREAD_GETNAME_TAKES_3ARGS",
        "AWS_PTHREAD_SETNAME_TAKES_2ARGS",
        "AWS_TEST_REGION=US_EAST_1",
        "CJSON_HIDE_SYMBOLS",
        "ENABLED_REQUEST_COMPRESSION",
        "ENABLED_ZLIB_REQUEST_COMPRESSION",
        "ENABLE_CURL_CLIENT",
        "ENFORCE_TLS_V1_2",
        "HAVE_SYSCONF",
        "INTEL_NO_ITTNOTIFY_API",
        "PLATFORM_LINUX",
        "USE_SIMD_ENCODING",
        "_POSIX_C_SOURCE=200809L",
        "_XOPEN_SOURCE=500",
    ],
    deps = [":aws-cpp-sdk-core"],
)

genrule(
    name = "config_h_in",
    outs = ["crt/aws-crt-cpp/crt/aws-c-common/include/aws/common/config.h.in"],
    cmd = "\n".join([
        "cat <<'EOF' >$@",
        "#ifndef AWS_COMMON_CONFIG_H",
        "#define AWS_COMMON_CONFIG_H",
        "",
        "#define AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS",
        "#define AWS_HAVE_GCC_INLINE_ASM",
        "/* #undef AWS_HAVE_MSVC_INTRINSICS_X64 */",
        "#define AWS_HAVE_POSIX_LARGE_FILE_SUPPORT",
        "#define AWS_HAVE_EXECINFO",
        "/* #undef AWS_HAVE_WINAPI_DESKTOP */",
        "#define AWS_HAVE_LINUX_IF_LINK_H",
        "#define AWS_HAVE_AVX2_INTRINSICS",
        "#define AWS_HAVE_AVX512_INTRINSICS",
        "#define AWS_HAVE_MM256_EXTRACT_EPI64",
        "#define AWS_HAVE_CLMUL",
        "/* #undef AWS_HAVE_ARM32_CRC */",
        "/* #undef AWS_HAVE_ARMv8_1 */",
        "/* #undef AWS_ARCH_ARM64 */",
        "#define AWS_ARCH_INTEL",
        "#define AWS_ARCH_INTEL_X64",
        "#define AWS_USE_CPU_EXTENSIONS",
        "",
        "#endif",
        "EOF",
    ]),
)

template_rule(
    name = "config_h",
    src = ":config_h_in",
    out = "crt/aws-crt-cpp/crt/aws-c-common/include/aws/common/config.h",
    substitutions = select({
        "@platforms//os:linux": {
        },
        "@platforms//os:osx": {
        },
        "@platforms//os:windows": {
        },
        "//conditions:default": {},
    }) | select({
        "@tbox//bazel:osx_clang": {
        },
        "//conditions:default": {},
    }),
)

genrule(
    name = "crt_config_h",
    outs = ["crt/aws-crt-cpp/include/aws/crt/Config.h"],
    cmd = "\n".join([
        "cat <<'EOF' >$@",
        "#pragma once",
        "/**",
        " * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.",
        " * SPDX-License-Identifier: Apache-2.0.",
        " */",
        "",
        "#define AWS_CRT_CPP_VERSION \"0.28.2\"",
        "#define AWS_CRT_CPP_VERSION_MAJOR 0",
        "#define AWS_CRT_CPP_VERSION_MINOR 28",
        "#define AWS_CRT_CPP_VERSION_PATCH 2",
        "#define AWS_CRT_CPP_GIT_HASH \"e14c814728dc438a0b7dc694bd83418addc5a6a1\"",
        "EOF",
    ]),
)
