load("@cc_toolchains//toolchain:cc_toolchains_setup.bzl", "cc_toolchains_setup")

def cc_toolchains_register():
    cc_toolchains_setup(
        name = "cc_toolchains_setup",
        toolchains = {
            "x86_64": {
                "linux": [
                    {
                        "distro": "generic",
                        "libc": "glibc",
                        "compiler": "gcc",
                        "triple": "x86_64-pc-linux-gnu",
                        "url": "https://blog.xiedeacc.com/files/gcc14.1.0-linux-x86_64_toolchain.tar.gz",
                        "strip_prefix": "gcc14.1.0-linux-x86_64_toolchain",
                        "sha256sum": "6e6a8a5c33a5e4d64a198619a7b34746be6dee1da2a734396dde8f851b63910c",
                        "sysroot": "@cc_toolchain_repo_x86_64_linux_generic_glibc_gcc",
                        "tool_names": {
                            "ar": "gcc-ar",
                            "as": "as",
                            "c++": "c++",
                            "cpp": "cpp",
                            "g++": "g++",
                            "gcc": "gcc",
                            "gcov": "gcov",
                            "ld": "ld",
                            "llvm-cov": "gcov",
                            "nm": "gcc-nm",
                            "objcopy": "objcopy",
                            "objdump": "objdump",
                            "strip": "strip",
                        },
                        "cxx_builtin_include_directories": [
                            "/usr/include/x86_64-linux-gnu",
                            "/usr/include",
                            "include/c++/14.1.0/x86_64-pc-linux-gnu",
                            "include/c++/14.1.0",
                            "include/c++/14.1.0/backward",
                            "lib/gcc/x86_64-pc-linux-gnu/14.1.0/include",
                            "lib/gcc/x86_64-pc-linux-gnu/14.1.0/include-fixed",
                        ],
                        "lib_directories": [
                            "lib64",
                            "lib/gcc/x86_64-pc-linux-gnu/14.1.0",
                            "/usr/lib/x86_64-linux-gnu",
                        ],
                        "supports_start_end_lib": True,
                        "debug": True,
                    },
                    {
                        "distro": "generic",
                        "libc": "glibc",
                        "compiler": "clang",
                        "triple": "x86_64-unknown-linux-gnu",
                        "url": "https://blog.xiedeacc.com/files/clang18.1.8-linux-x86_64_toolchain.tar.gz",
                        "strip_prefix": "clang18.1.8-linux-x86_64_toolchain",
                        "sha256sum": "be64a29251dd2b7ae6e8e783f99ab395b4bf2a75f98d8a6e03bf855e9d811434",
                        "sysroot": "@cc_toolchain_repo_x86_64_linux_generic_glibc_clang",
                        "tool_names": {
                            "ar": "llvm-ar",
                            "as": "llvm-as",
                            "c++": "clang++",
                            "cpp": "clang-cpp",
                            "g++": "clang++",
                            "gcc": "clang",
                            "gcov": "llvm-cov",
                            "ld": "ld.lld",
                            "llvm-cov": "llvm-cov",
                            "nm": "llvm-nm",
                            "objcopy": "llvm-objcopy",
                            "objdump": "llvm-objdump",
                            "strip": "llvm-strip",
                        },
                        "cxx_builtin_include_directories": [
                            "/usr/include/x86_64-linux-gnu",
                            "/usr/include",
                            "include/x86_64-unknown-linux-gnu/c++/v1",
                            "include/c++/v1",
                            "lib/clang/18/include",
                            "lib/clang/18/share",
                            "include",
                        ],
                        "lib_directories": [
                            "lib",
                            "lib/x86_64-unknown-linux-gnu",
                            "lib/clang/18/lib/x86_64-unknown-linux-gnu",
                            "/usr/lib/x86_64-linux-gnu",
                        ],
                        "link_libs": [
                            "libclang_rt.builtins.a",
                        ],
                        "supports_start_end_lib": True,
                        "debug": True,
                    },
                ],
                "osx": [
                    {
                        "distro": "generic",
                        "libc": "macosx",
                        "compiler": "gcc",
                        "triple": "x86_64-apple-darwin23.3",
                        "url": "https://blog.xiedeacc.com/files/gcc14.1.0-darwin23.3-x86_64_toolchain.tar.gz",
                        "strip_prefix": "gcc14.1.0-darwin23.3-x86_64_toolchain",
                        "sha256sum": "e9fab8943971a4f9733d41c7106e3349ea9e26a2c08f98194cba38d3bfa34d5c",
                        "sysroot": "@macosx14.2-x86_64_sysroot",
                        "tool_names": {
                            "ar": "x86_64-apple-darwin23.3-libtool",
                            #"ar": "x86_64-apple-darwin23.3-ar",
                            "as": "x86_64-apple-darwin23.3-as",
                            "c++": "x86_64-apple-darwin23.3-g++",
                            "cpp": "x86_64-apple-darwin23.3-cpp",
                            "g++": "x86_64-apple-darwin23.3-g++",
                            "gcc": "x86_64-apple-darwin23.3-gcc",
                            "gcov": "x86_64-apple-darwin23.3-gcov",
                            "ld": "ld",
                            "llvm-cov": "None",
                            "nm": "x86_64-apple-darwin23.3-nm",
                            "objcopy": "x86_64-apple-darwin-objcopy",
                            "objdump": "x86_64-apple-darwin-objdump",
                            "strip": "x86_64-apple-darwin23.3-strip",
                        },
                        "cxx_builtin_include_directories": [
                            "x86_64-apple-darwin23.3/include/c++/14.1.0/x86_64-apple-darwin23.3",
                            "x86_64-apple-darwin23.3/include/c++/14.1.0",
                            "x86_64-apple-darwin23.3/include/c++/14.1.0/backward",
                            "lib/gcc/x86_64-apple-darwin23.3/14.1.0/include",
                            "lib/gcc/x86_64-apple-darwin23.3/14.1.0/include-fixed",
                        ],
                        "lib_directories": [
                            "x86_64-apple-darwin23.3/lib",
                            "lib",
                        ],
                        "sysroot_include_directories": [
                            "usr/include",
                            "System/Library/Frameworks",
                        ],
                        "sysroot_lib_directories": [
                            "usr/lib",
                        ],
                        "supports_start_end_lib": False,
                        "debug": True,
                    },
                    {
                        "distro": "generic",
                        "libc": "macosx",
                        "compiler": "clang",
                        "triple": "x86_64-apple-darwin",
                        "url": "https://blog.xiedeacc.com/files/clang18.1.8-linux-x86_64_toolchain.tar.gz",
                        "strip_prefix": "clang18.1.8-linux-x86_64_toolchain",
                        "sha256sum": "be64a29251dd2b7ae6e8e783f99ab395b4bf2a75f98d8a6e03bf855e9d811434",
                        "sysroot": "@macosx14.2-x86_64_sysroot",
                        "tool_names": {
                            "ar": "x86_64-apple-darwin23.3-libtool",
                            "as": "x86_64-apple-darwin23.3-as",
                            "c++": "clang++",
                            "cpp": "clang-cpp",
                            "g++": "clang++",
                            "gcc": "clang",
                            "gcov": "x86_64-apple-darwin23.3-gcov",
                            "ld": "ld64",
                            "llvm-cov": "None",
                            "nm": "x86_64-apple-darwin23.3-nm",
                            "objcopy": "x86_64-apple-darwin-objcopy",
                            "objdump": "x86_64-apple-darwin-objdump",
                            "strip": "x86_64-apple-darwin23.3-strip",
                        },
                        "cxx_builtin_include_directories": [
                        ],
                        "lib_directories": [
                        ],
                        "sysroot_include_directories": [
                            "llvm18.1.8/include/c++/v1",
                            "llvm18.1.8/lib/clang/18/include",
                            "usr/include",
                            "System/Library/Frameworks",
                        ],
                        "sysroot_lib_directories": [
                            "llvm18.1.8/lib",
                            "llvm18.1.8/lib/clang/18/lib/darwin",
                            "usr/lib",
                        ],
                        "link_libs": [
                            "libclang_rt.osx.a",
                        ],
                        "supports_start_end_lib": False,
                        "debug": True,
                    },
                ],
            },
            "aarch64": {
                "linux": [
                    {
                        "distro": "openwrt",
                        "libc": "musl",
                        "compiler": "gcc",
                        "triple": "aarch64-openwrt-linux-musl",
                        "url": "https://blog.xiedeacc.com/files/gcc12.3.0-openwrt23.4-aarch64_toolchain.tar.gz",
                        "strip_prefix": "gcc12.3.0-openwrt23.4-aarch64_toolchain",
                        "sha256sum": "03f9bfda848f9d044ec3f4cebf1fce1f82f9c6363d9a3ef36affae522590f52a",
                        "sysroot": "@cc_toolchain_repo_aarch64_linux_openwrt_musl_gcc",
                        "tool_names": {
                            "ar": "aarch64-openwrt-linux-musl-ar",
                            "as": "aarch64-openwrt-linux-musl-as.bin",
                            "ld": "aarch64-openwrt-linux-musl-ld.bin",
                            "llvm-cov": "aarch64-openwrt-linux-musl-gcov.bin",
                            "gcov": "aarch64-openwrt-linux-musl-gcov.bin",
                            "cpp": "aarch64-openwrt-linux-musl-cpp.bin",
                            "gcc": "aarch64-openwrt-linux-musl-gcc.bin",
                            "nm": "aarch64-openwrt-linux-musl-nm.bin",
                            "objcopy": "aarch64-openwrt-linux-musl-objcopy.bin",
                            "objdump": "aarch64-openwrt-linux-musl-objdump.bin",
                            "strip": "aarch64-openwrt-linux-musl-strip.bin",
                        },
                        "cxx_builtin_include_directories": [
                            "aarch64-openwrt-linux-musl/include/c++/12.3.0/aarch64-openwrt-linux-musl",
                            "aarch64-openwrt-linux-musl/include/c++/12.3.0",
                            "aarch64-openwrt-linux-musl/include/c++/12.3.0/backward",
                            "lib/gcc/aarch64-openwrt-linux-musl/12.3.0/include",
                            "lib/gcc/aarch64-openwrt-linux-musl/12.3.0/include-fixed",
                            "include",
                        ],
                        "lib_directories": [],
                        "sysroot_include_directories": [],
                        "sysroot_lib_directories": [
                            "lib/gcc/aarch64-openwrt-linux-musl/12.3.0",
                            "lib",
                        ],
                        "link_libs": [
                            "libgcc.a",
                        ],
                        "supports_start_end_lib": True,
                        "debug": True,
                    },
                    {
                        "distro": "generic",
                        "libc": "glibc",
                        "compiler": "clang",
                        "triple": "aarch64-unknown-linux-gnu",
                        "url": "https://blog.xiedeacc.com/files/clang18.1.8-linux-x86_64_toolchain.tar.gz",
                        "strip_prefix": "clang18.1.8-linux-x86_64_toolchain",
                        "sha256sum": "be64a29251dd2b7ae6e8e783f99ab395b4bf2a75f98d8a6e03bf855e9d811434",
                        "sysroot": "@clang18.1.8-aarch64_sysroot",
                        "tool_names": {
                            "ar": "llvm-ar",
                            "as": "llvm-as",
                            "c++": "clang++",
                            "cpp": "clang-cpp",
                            "g++": "clang++",
                            "gcc": "clang",
                            "gcov": "llvm-cov",
                            "ld": "ld",
                            "llvm-cov": "llvm-cov",
                            "nm": "llvm-nm",
                            "objcopy": "llvm-objcopy",
                            "objdump": "llvm-objdump",
                            "strip": "llvm-strip",
                        },
                        "cxx_builtin_include_directories": [
                        ],
                        "lib_directories": [
                        ],
                        "sysroot_include_directories": [
                            "include/aarch64-unknown-linux-gnu/c++/v1",
                            "include/c++/v1",
                            "lib/clang/18/include",
                            "usr/include",
                        ],
                        "sysroot_lib_directories": [
                            "lib",
                            "lib/aarch64-unknown-linux-gnu",
                            "lib/clang/18/lib/aarch64-unknown-linux-gnu",
                            "usr/lib",
                        ],
                        "link_libs": [
                            "libclang_rt.builtins.a",
                            "Scrt1.o",
                            "crti.o",
                            "crtbeginS.o",
                            "crtendS.o",
                            "crtn.o",
                        ],
                        "supports_start_end_lib": True,
                        "debug": True,
                    },
                ],
            },
        },
    )
