load("@cc_toolchains//toolchain:cc_toolchains_setup.bzl", "cc_toolchains_setup")

def cc_toolchains_register():
    cc_toolchains_setup(
        name = "cc_toolchains_setup",
        toolchains = {
            "x86_64": {
                "linux": [
                    {
                        "vendor": "unknown",
                        "distro": "generic",
                        "libc": "gnu",
                        "compiler": "clang",
                        "triple": "x86_64-unknown-linux-gnu",
                        "url": "https://blog.xiedeacc.com/files/clang18.1.8-linux-x86_64_toolchain.tar.gz",
                        "strip_prefix": "clang18.1.8-linux-x86_64_toolchain",
                        "sha256sum": "be64a29251dd2b7ae6e8e783f99ab395b4bf2a75f98d8a6e03bf855e9d811434",
                        "sysroot": "@linux-x86_64-gnu_sysroot",
                        "tool_names": {
                            "ar": "llvm-ar",
                            "as": "llvm-as",
                            "c++": "clang++",
                            "cpp": "clang-cpp",
                            "g++": "clang++",
                            "gcc": "clang",
                            "gcov": "llvm-cov",
                            "ld": "ld.lld",
                            "llvm-cov": "llvm-cov",
                            "nm": "llvm-nm",
                            "objcopy": "llvm-objcopy",
                            "objdump": "llvm-objdump",
                            "strip": "llvm-strip",
                        },
                        "cxx_builtin_include_directories": [
                            "/usr/include/x86_64-linux-gnu",
                            "/usr/include",
                            "include/x86_64-unknown-linux-gnu/c++/v1",
                            "include/c++/v1",
                            "lib/clang/18/include",
                            "lib/clang/18/share",
                            "include",
                        ],
                        "lib_directories": [
                            "lib",
                            "lib/x86_64-unknown-linux-gnu",
                            "lib/clang/18/lib/x86_64-unknown-linux-gnu",
                            "/usr/lib/x86_64-linux-gnu",
                        ],
                        "link_libs": [],
                        "supports_start_end_lib": True,
                        "debug": True,
                    },
                ],
                "osx": [
                    {
                        "vendor": "unknown",
                        "distro": "generic",
                        "libc": "macosx",
                        "compiler": "clang",
                        "triple": "x86_64-apple-darwin",
                        "url": "https://blog.xiedeacc.com/files/clang18.1.8-linux-x86_64_toolchain.tar.gz",
                        "strip_prefix": "clang18.1.8-linux-x86_64_toolchain",
                        "sha256sum": "be64a29251dd2b7ae6e8e783f99ab395b4bf2a75f98d8a6e03bf855e9d811434",
                        "sysroot": "@macosx14.2-x86_64_sysroot",
                        "tool_names": {
                            "ar": "x86_64-apple-darwin23.3-libtool",
                            "as": "x86_64-apple-darwin23.3-as",
                            "c++": "clang++",
                            "cpp": "clang-cpp",
                            "g++": "clang++",
                            "gcc": "clang",
                            "gcov": "x86_64-apple-darwin23.3-gcov",
                            "ld": "ld64",
                            "llvm-cov": "None",
                            "nm": "x86_64-apple-darwin23.3-nm",
                            "objcopy": "x86_64-apple-darwin-objcopy",
                            "objdump": "x86_64-apple-darwin-objdump",
                            "strip": "x86_64-apple-darwin23.3-strip",
                        },
                        "cxx_builtin_include_directories": [
                        ],
                        "lib_directories": [
                        ],
                        "sysroot_include_directories": [
                            "llvm18.1.8/include/c++/v1",
                            "llvm18.1.8/lib/clang/18/include",
                            "usr/include",
                            "System/Library/Frameworks",
                        ],
                        "sysroot_lib_directories": [
                            "llvm18.1.8/lib",
                            "llvm18.1.8/lib/clang/18/lib/darwin",
                            "usr/lib",
                        ],
                        "link_libs": [
                            "libclang_rt.osx.a",
                        ],
                        "supports_start_end_lib": False,
                        "debug": True,
                    },
                ],
            },
            "aarch64": {
                "linux": [
                    {
                        "vendor": "openwrt",
                        "distro": "openwrt",
                        "libc": "musl",
                        "compiler": "gcc",
                        "triple": "aarch64-openwrt-linux-musl",
                        "url": "https://blog.xiedeacc.com/files/gcc12.3.0-openwrt23.4-aarch64_toolchain.tar.gz",
                        "strip_prefix": "gcc12.3.0-openwrt23.4-aarch64_toolchain",
                        "sha256sum": "03f9bfda848f9d044ec3f4cebf1fce1f82f9c6363d9a3ef36affae522590f52a",
                        "sysroot": "@cc_toolchain_repo_gcc_aarch64_openwrt_linux_musl",
                        "tool_names": {
                            "ar": "aarch64-openwrt-linux-musl-ar",
                            "as": "aarch64-openwrt-linux-musl-as.bin",
                            "ld": "aarch64-openwrt-linux-musl-ld.bin",
                            "llvm-cov": "aarch64-openwrt-linux-musl-gcov.bin",
                            "gcov": "aarch64-openwrt-linux-musl-gcov.bin",
                            "cpp": "aarch64-openwrt-linux-musl-cpp.bin",
                            "gcc": "aarch64-openwrt-linux-musl-gcc.bin",
                            "nm": "aarch64-openwrt-linux-musl-nm.bin",
                            "objcopy": "aarch64-openwrt-linux-musl-objcopy.bin",
                            "objdump": "aarch64-openwrt-linux-musl-objdump.bin",
                            "strip": "aarch64-openwrt-linux-musl-strip.bin",
                        },
                        "cxx_builtin_include_directories": [
                            "aarch64-openwrt-linux-musl/include/c++/12.3.0/aarch64-openwrt-linux-musl",
                            "aarch64-openwrt-linux-musl/include/c++/12.3.0",
                            "aarch64-openwrt-linux-musl/include/c++/12.3.0/backward",
                            "lib/gcc/aarch64-openwrt-linux-musl/12.3.0/include",
                            "lib/gcc/aarch64-openwrt-linux-musl/12.3.0/include-fixed",
                            "include",
                        ],
                        "lib_directories": [
                            "lib/gcc/aarch64-openwrt-linux-musl/12.3.0",
                            "lib",
                        ],
                        "sysroot_include_directories": [
                            "aarch64-openwrt-linux-musl/include",
                            "include",
                        ],
                        "sysroot_lib_directories": [
                            "lib/gcc/aarch64-openwrt-linux-musl/12.3.0",
                            "lib",
                        ],
                        "link_libs": [
                            "libgcc.a",
                        ],
                        "supports_start_end_lib": True,
                        "debug": True,
                    },
                    {
                        "vendor": "unknown",
                        "distro": "generic",
                        "libc": "gnu",
                        "compiler": "clang",
                        "triple": "aarch64-unknown-linux-gnu",
                        "url": "https://blog.xiedeacc.com/files/clang18.1.8-linux-x86_64_toolchain.tar.gz",
                        "strip_prefix": "clang18.1.8-linux-x86_64_toolchain",
                        "sha256sum": "be64a29251dd2b7ae6e8e783f99ab395b4bf2a75f98d8a6e03bf855e9d811434",
                        "sysroot": "@linux-aarch64-gnu_sysroot",
                        "tool_names": {
                            "ar": "llvm-ar",
                            "as": "llvm-as",
                            "c++": "clang++",
                            "cpp": "clang-cpp",
                            "g++": "clang++",
                            "gcc": "clang",
                            "gcov": "llvm-cov",
                            "ld": "ld.lld",
                            "llvm-cov": "llvm-cov",
                            "nm": "llvm-nm",
                            "objcopy": "llvm-objcopy",
                            "objdump": "llvm-objdump",
                            "strip": "llvm-strip",
                        },
                        "cxx_builtin_include_directories": [
                            "include/x86_64-unknown-linux-gnu/c++/v1",
                            "include/c++/v1",
                            "lib/clang/18/include",
                            "lib/clang/18/share",
                            "include",
                        ],
                        "lib_directories": [
                            "lib",
                            "lib/x86_64-unknown-linux-gnu",
                            "lib/clang/18/lib/x86_64-unknown-linux-gnu",
                        ],
                        "sysroot_include_directories": [
                            "usr/include",
                        ],
                        "sysroot_lib_directories": [
                            "lib",
                            "usr/lib",
                        ],
                        "link_libs": [],
                        "supports_start_end_lib": True,
                        "debug": True,
                    },
                    {
                        "vendor": "unknown",
                        "distro": "generic",
                        "libc": "musl",
                        "compiler": "gcc",
                        "triple": "aarch64-unknown-linux-musl",
                        "url": "https://blog.xiedeacc.com/files/gcc14.2.0-aarch64-unknown-linux-musl.tar.gz",
                        "strip_prefix": "gcc14.2.0-aarch64-unknown-linux-musl",
                        "sha256sum": "df50a1807433bf1f8eaeaeaecf8c53aa12e72e5285fb539c7b64532833f017a4",
                        "sysroot": "@linux-aarch64-musl_sysroot",
                        #"url": "/zfs/www/files/gcc14.2.0-aarch64-unknown-linux-musl",
                        #"sysroot": "/zfs/www/files/linux-aarch64-musl_sysroot",
                        "tool_names": {
                            "ar": "aarch64-unknown-linux-musl-ar",
                            "as": "aarch64-unknown-linux-musl-as",
                            "c++": "aarch64-unknown-linux-musl-c++",
                            "cpp": "aarch64-unknown-linux-musl-cpp",
                            "g++": "aarch64-unknown-linux-musl-g++",
                            "gcc": "aarch64-unknown-linux-musl-gcc",
                            "gcov": "aarch64-unknown-linux-musl-gcov",
                            "ld": "aarch64-unknown-linux-musl-ld",
                            "llvm-cov": "aarch64-unknown-linux-musl-gcov",
                            "nm": "aarch64-unknown-linux-musl-nm",
                            "objcopy": "aarch64-unknown-linux-musl-objcopy",
                            "objdump": "aarch64-unknown-linux-musl-objdump",
                            "strip": "aarch64-unknown-linux-musl-strip",
                        },
                        "cxx_builtin_include_directories": [
                            "aarch64-unknown-linux-musl/include/c++/14.2.0/aarch64-unknown-linux-musl",
                            "aarch64-unknown-linux-musl/include/c++/14.2.0",
                            "aarch64-unknown-linux-musl/include/c++/14.2.0/backward",
                            "lib/gcc/aarch64-unknown-linux-musl/14.2.0/include",
                            "lib/gcc/aarch64-unknown-linux-musl/14.2.0/include-fixed",
                        ],
                        "sysroot_include_directories": [
                            "usr/include",
                        ],
                        "lib_directories": [
                            "lib",
                            "lib/gcc/aarch64-unknown-linux-musl/14.2.0",
                        ],
                        "sysroot_lib_directories": [
                            "lib",
                            "usr/lib",
                        ],
                        "link_libs": [],
                        "link_flags": [
                            "-lstdc++",
                            "-lm",
                        ],
                        "supports_start_end_lib": False,
                        "debug": True,
                    },
                ],
            },
        },
    )
