#!/bin/bash

set -euo pipefail

SERVICE_NAME="tbox_client"
BINARY_NAME="tbox_client"
REMOTE="${REMOTE:-root@openwrt}"
if [[ "${REMOTE}" != *@* ]]; then
    echo "REMOTE must use the explicit user@HostAlias form (for example, root@openwrt)." >&2
    exit 1
fi
INSTALL_DIR="/usr/local/tbox"
BIN_DIR="${INSTALL_DIR}/bin"
CONF_DIR="${INSTALL_DIR}/conf"
DATA_DIR="${INSTALL_DIR}/data"
LOG_DIR="${INSTALL_DIR}/logs"
WORKSPACE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BAZEL_CONFIG="gcc_aarch64_linux_musl"
BAZEL_TARGET="//src/client:tbox_client"
LOCAL_BINARY="${WORKSPACE_ROOT}/bazel-bin/src/client/${BINARY_NAME}"

cd "${WORKSPACE_ROOT}"
bazel build --config="${BAZEL_CONFIG}" "${BAZEL_TARGET}"

if [[ ! -x "${LOCAL_BINARY}" ]]; then
    echo "Missing ${LOCAL_BINARY}; build --config=${BAZEL_CONFIG} ${BAZEL_TARGET} before deploying." >&2
    exit 1
fi

ssh "${REMOTE}" "mkdir -p ${BIN_DIR} ${CONF_DIR} ${DATA_DIR} ${LOG_DIR}"
ssh "${REMOTE}" "/etc/init.d/${SERVICE_NAME} stop 2>/dev/null || true"

TEMP_BINARY="$(mktemp /tmp/tbox_client.XXXXXX)"
TEMP_CONFIG="$(mktemp /tmp/tbox_client_config.XXXXXX)"
trap 'rm -f "${TEMP_BINARY}" "${TEMP_CONFIG}"' EXIT
cp "${LOCAL_BINARY}" "${TEMP_BINARY}"
if command -v llvm-strip >/dev/null 2>&1; then
    llvm-strip --strip-unneeded "${TEMP_BINARY}"
elif command -v aarch64-linux-gnu-strip >/dev/null 2>&1; then
    aarch64-linux-gnu-strip --strip-unneeded "${TEMP_BINARY}"
else
    echo "No strip tool found for ${BINARY_NAME}; refusing to deploy an unstripped binary." >&2
    exit 1
fi

python3 "${WORKSPACE_ROOT}/deploy/prepare_config.py" client \
    "${WORKSPACE_ROOT}/conf/client_openwrt_config.json" "${TEMP_CONFIG}" \
    --host openwrt \
    --credentials-from "${WORKSPACE_ROOT}/conf/client_local_config.json"
if ! ssh "${REMOTE}" "test -x /etc/init.d/${SERVICE_NAME}"; then
    echo "Missing /etc/init.d/${SERVICE_NAME} on ${REMOTE}. Install or migrate the procd init once on the target host before deploying; it must not be stored in this repository or generated by this deploy script." >&2
    exit 1
fi
scp "${TEMP_BINARY}" "${REMOTE}:${BIN_DIR}/${BINARY_NAME}.new"
scp "${TEMP_CONFIG}" "${REMOTE}:${CONF_DIR}/client_config.json"
ssh "${REMOTE}" "mkdir -p ~/.ssh && chmod 700 ~/.ssh"
if ! ssh "${REMOTE}" "test -s ~/.ssh/id_ed25519 -a -s ~/.ssh/id_ed25519.pub"; then
    scp ~/.ssh/id_ed25519 ~/.ssh/id_ed25519.pub "${REMOTE}:~/.ssh/"
    ssh "${REMOTE}" "chmod 600 ~/.ssh/id_ed25519 && chmod 644 ~/.ssh/id_ed25519.pub"
fi
ssh "${REMOTE}" "chmod 755 ${BIN_DIR}/${BINARY_NAME}.new && mv -f ${BIN_DIR}/${BINARY_NAME}.new ${BIN_DIR}/${BINARY_NAME} && chmod 644 ${CONF_DIR}/client_config.json"

ssh "${REMOTE}" "for ca_source in /etc/ssl/certs/ca-certificates.crt /etc/ssl/cert.pem; do if test -s \"\${ca_source}\"; then cp -f \"\${ca_source}\" ${CONF_DIR}/ca-bundle.pem && chmod 644 ${CONF_DIR}/ca-bundle.pem && exit 0; fi; done; echo 'No system CA bundle found on OpenWrt' >&2; exit 1"
ssh "${REMOTE}" "rm -f ${CONF_DIR}/xiedeacc.com.ca.cer"
ssh "${REMOTE}" "rm -f ${LOG_DIR}/tbox_client*.log*"

ssh "${REMOTE}" "/etc/init.d/${SERVICE_NAME} enable && /etc/init.d/${SERVICE_NAME} restart"
sleep 2
ssh "${REMOTE}" "/etc/init.d/${SERVICE_NAME} running"
echo "Deployed ${BINARY_NAME} to ${REMOTE}:${BIN_DIR}/${BINARY_NAME}"
